#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing wkhtmltox ..."
COMMAND=$(cat <<EOF
apt-get -y  update 
apt-get install -y wget xfonts-base xfonts-75dpi
cd /tmp && wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
cd /tmp && dpkg -i wkhtmltox_0.12.5-1.trusty_amd64.deb
cd /tmp apt-get install -f
echo "-----> wkhtmltox installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
